databases:
  presto:
    jdbc_url: "jdbc:trino://${databases.presto.host}:${databases.presto.port}/hive/${databases.hive.schema}?\
      SSL=true&\
      SSLTrustStorePath=${databases.presto.https_keystore_path}&\
      SSLTrustStorePassword=${databases.presto.https_keystore_password}&\
      KerberosRemoteServiceName=${databases.presto.cli_kerberos_service_name}&\
      KerberosUseCanonicalHostname=${databases.presto.cli_kerberos_use_canonical_hostname}&\
      KerberosDelegation=true"
    kerberos_principal: ${databases.presto.cli_kerberos_principal}
    kerberos_keytab: ${databases.presto.cli_kerberos_keytab}
