databases:
  presto:
    host: presto-master
    port: 7778
    http_port: 8080
    https_port: ${databases.presto.port}
    server_address: https://${databases.presto.host}:${databases.presto.port}
    jdbc_url: "jdbc:trino://${databases.presto.host}:${databases.presto.port}?\
      SSL=true&\
      SSLTrustStorePath=${databases.presto.https_keystore_path}&\
      SSLTrustStorePassword=${databases.presto.https_keystore_password}&\
      externalAuthentication=true"
    https_keystore_path: /docker/presto-product-tests/truststore.jks
    https_keystore_password: '123456'
