databases:
  presto:
    jdbc_user: root
  delta:
    jdbc_driver_class: ${DATABRICKS_TEST_JDBC_DRIVER_CLASS}
    schema: default
    prepare_statement:
      - USE ${databases.delta.schema}
    table_manager_type: jdbc
    jdbc_url: ${DATABRICKS_TEST_JDBC_URL}
    jdbc_user: ${DATABRICKS_TEST_LOGIN}
    jdbc_password: ${DATABRICKS_TEST_TOKEN}

s3:
  server_type: aws
