name: "Pull Request Labeler"

on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

# NOTE: Do not check out/execute code from the PR since a read-write token is present due to pull_request_target
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # Do not sync labels as this reverts manually added "tests:hive" label.
          # Syncing labels requires that we define "components" labels.
          # See https://github.com/actions/labeler/issues/112#issuecomment-999953377 for why an empty string instead of false.
          sync-labels: ''
          configuration-path: .github/config/labeler-config.yml
